0 127.0.0.1:50001 127.0.0.1:50002 /home/rkerur/FlexRaft-Code/data/raft_log0 /home/rkerur/FlexRaft-Code/data/testdb0
1 127.0.0.1:50003 127.0.0.1:50004 /home/rkerur/FlexRaft-Code/data/raft_log1 /home/rkerur/FlexRaft-Code/data/testdb1
2 127.0.0.1:50005 127.0.0.1:50006 /home/rkerur/FlexRaft-Code/data/raft_log2 /home/rkerur/FlexRaft-Code/data/testdb2
3 127.0.0.1:50007 127.0.0.1:50008 /home/rkerur/FlexRaft-Code/data/raft_log3 /home/rkerur/FlexRaft-Code/data/testdb3
4 127.0.0.1:50009 127.0.0.1:50010 /home/rkerur/FlexRaft-Code/data/raft_log4 /home/rkerur/FlexRaft-Code/data/testdb4